export const mockSchedule = {
  MRData: {
    xmlns: "http://ergast.com/mrd/1.4",
    series: "f1",
    url: "http://ergast.com/api/f1/2021.json",
    limit: "30",
    offset: "0",
    total: "23",
    RaceTable: {
      season: "2021",
      Races: [
        {
          season: "2021",
          round: "1",
          url: "https://en.wikipedia.org/wiki/2021_Bahrain_Grand_Prix",
          raceName: "Bahrain Grand Prix",
          Circuit: {
            circuitId: "bahrain",
            url: "http://en.wikipedia.org/wiki/Bahrain_International_Circuit",
            circuitName: "Bahrain International Circuit",
            Location: {
              lat: "26.0325",
              long: "50.5106",
              locality: "Sakhir",
              country: "Bahrain",
            },
          },
          date: "2021-03-28",
          time: "15:00:00Z",
        },
        {
          season: "2021",
          round: "2",
          url: "http://en.wikipedia.org/wiki/2021_Emilia_Romagna_Grand_Prix",
          raceName: "Emilia Romagna Grand Prix",
          Circuit: {
            circuitId: "imola",
            url: "http://en.wikipedia.org/wiki/Autodromo_Enzo_e_Dino_Ferrari",
            circuitName: "Autodromo Enzo e Dino Ferrari",
            Location: {
              lat: "44.3439",
              long: "11.7167",
              locality: "Imola",
              country: "Italy",
            },
          },
          date: "2021-04-18",
          time: "13:00:00Z",
        },
        {
          season: "2021",
          round: "3",
          url: "http://en.wikipedia.org/wiki/2021_Portuguese_Grand_Prix",
          raceName: "Portuguese Grand Prix",
          Circuit: {
            circuitId: "portimao",
            url: "http://en.wikipedia.org/wiki/Algarve_International_Circuit",
            circuitName: "Autódromo Internacional do Algarve",
            Location: {
              lat: "37.227",
              long: "-8.6267",
              locality: "Portimão",
              country: "Portugal",
            },
          },
          date: "2021-05-02",
          time: "13:00:00Z",
        },
        {
          season: "2021",
          round: "4",
          url: "http://en.wikipedia.org/wiki/2021_Spanish_Grand_Prix",
          raceName: "Spanish Grand Prix",
          Circuit: {
            circuitId: "catalunya",
            url: "http://en.wikipedia.org/wiki/Circuit_de_Barcelona-Catalunya",
            circuitName: "Circuit de Barcelona-Catalunya",
            Location: {
              lat: "41.57",
              long: "2.26111",
              locality: "Montmeló",
              country: "Spain",
            },
          },
          date: "2021-05-09",
          time: "13:00:00Z",
        },
        {
          season: "2021",
          round: "5",
          url: "http://en.wikipedia.org/wiki/2021_Monaco_Grand_Prix",
          raceName: "Monaco Grand Prix",
          Circuit: {
            circuitId: "monaco",
            url: "http://en.wikipedia.org/wiki/Circuit_de_Monaco",
            circuitName: "Circuit de Monaco",
            Location: {
              lat: "43.7347",
              long: "7.42056",
              locality: "Monte-Carlo",
              country: "Monaco",
            },
          },
          date: "2021-05-23",
          time: "13:00:00Z",
        },
      ],
    },
  },
};
